apiVersion: v1
kind: Secret
metadata:
  name: "vault-secret"
  namespace: "default"
data:
  secret-id: JHDSGAHDJBSAHJBFDSVMCXVZLZDNGGDBFDSBFCMZXCJDSBV
  # echo -n "toot" | base64
  #                | Encode
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      # Path is the mount path of the Vault KV backend endpoint
      path: "secret"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      # vault enterprise namespace: https://www.vaultproject.io/docs/enterprise/namespaces
      namespace: "vault"
        # Kubernetes auth: https://www.vaultproject.io/docs/auth/kubernetes
      auth:
        appRole:
          path: "approle"
          roleId: "876dsds-3fe4-sadasd-1sdsde-84dsdsdsdsd87sd8"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "vault-secret"
            key: "secret-id"
            namespace: "default" # namespace where you can find the secret id for given app role 